services:
  - type: web
    name: seu-app-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # As variáveis de ambiente sensíveis (MONGO_URL, JWT_SECRET, CLOUDINARY_*) 
      # devem ser configuradas diretamente no painel da Render por segurança.
      # Exemplo:
      # - key: MONGO_URL
      #   sync: false # Indica que o valor será definido no painel da Render
      # - key: JWT_SECRET
      #   sync: false
      # - key: CLOUDINARY_CLOUD_NAME
      #   sync: false
      # - key: CLOUDINARY_API_KEY
      #   sync: false
      # - key: CLOUDINARY_API_SECRET
      #   sync: false
    healthCheckPath: /health # Use a rota de health check que você já tem
    # Para evitar problemas de cache quebrado ou 404 após inatividade, 
    # a configuração de SPA já está no seu index.js. 
    # A Render lida com a inatividade hibernando o serviço e reativando-o sob demanda.
    # Certifique-se de que seu health check esteja sempre funcionando.